In [1]:
import numpy as np
import pandas as pd

# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [2]:
# 2. Given a NumPy array 'arr', check if its data type is float64
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)

True


In [3]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [4]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr)

[1.1 2.2 3.3]


In [5]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

In [6]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality
def array_dimension(arr):
    return arr.ndim

In [7]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

In [8]:
# 9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2], [3, 4]])
print(array_strides(arr))

(16, 8)


In [9]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[5, 6, 7], [8, 9, 10]])
print(shape_stride_relationship(arr))


((2, 3), (24, 8))


In [10]:
# 11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [11]:
# 12. Write a function create_ones_matrix that takes integers rows and cols and generates a 2D NumPy array filled with ones of size rows x cols.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#  13. Write a function generate_range_array that takes start, stop, and step and creates a NumPy array with a range.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(2, 10, 2))


[2 4 6 8]


In [13]:
#  14. Design a function generate_linear_space that takes start, stop, and num and generates a NumPy array with num equally spaced values between start and stop.
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0.0, 1.0, 5))


[0.   0.25 0.5  0.75 1.  ]


In [14]:
#15. Create a function create_identity_matrix that takes an integer n and generates a square identity matrix of size n x n.
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_numpy_array(lst):
    return np.array(lst)

python_list = [1, 2, 3, 4]
print(list_to_numpy_array(python_list))


[1 2 3 4]


In [16]:
# 17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.
arr = np.array([10, 20, 30, 40])
view_arr = arr.view()
print(view_arr)

[10 20 30 40]


In [17]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(a, b, axis=0))  # vertical
print(concatenate_arrays(a, b, axis=1))  # horizontal


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.
x = np.array([[1], [2]])
y = np.array([[3, 4], [5, 6]])
result = np.concatenate((x, y), axis=1)
print(result)


[[1 3 4]
 [2 5 6]]


In [19]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arr_list):
    return np.vstack(arr_list)

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
print(vertical_stack([a, b, c]))

[[1 2]
 [3 4]
 [5 6]]


In [20]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))

[1 3 5 7 9]


In [21]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def equal_space_array():
    return np.linspace(0, 1, 10)

print(equal_space_array())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [22]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)
def logarithmic_space_array():
    return np.logspace(0, 3, 5)

print(logarithmic_space_array())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [23]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def logarithmic_space_array():
    return np.logspace(0, 3, 5)

print(logarithmic_space_array())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)

    A    B   C
0  13   13  24
1  19   27  57
2  47  100  74
3  92   29  44
4  40    6  72


In [25]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negatives(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

sample_df = pd.DataFrame({
    "A": [10, -5, 7, -2],
    "B": [1, 2, 3, 4]
})
print(replace_negatives(sample_df, "A"))

    A  B
0  10  1
1   0  2
2   7  3
3   0  4


In [26]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])


30


In [27]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr_2d[1, 2])


6


In [28]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])

[ 8 10  7]


In [29]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])


[3 4 5 6]


In [30]:
# 30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr_2d[0:2, 1:3])


[[2 3]
 [5 6]]


In [31]:
# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_by_indices(arr, indices):
    return arr.flat[indices]

arr = np.array([[10, 20, 30], [40, 50, 60]])
indices = [0, 4, 5]
print(extract_by_indices(arr, indices))

[10 50 60]


In [32]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr = np.array([2, 8, 3, 10, 6])
print(filter_greater_than(arr, 5))

[ 8 10  6]


In [33]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_from_3d(arr, x, y, z):
    return arr[x, y, z]

arr = np.arange(2*3*4).reshape(2, 3, 4)
x = np.array([0, 1])
y = np.array([1, 2])
z = np.array([2, 3])
print(extract_from_3d(arr, x, y, z))

[ 6 23]


In [34]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_both_conditions(arr):
    return arr[(arr > 3) & (arr < 8)]

arr = np.array([1, 4, 6, 8, 10])
print(filter_both_conditions(arr))


[4 6]


In [35]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_by_row_col(arr, row_idx, col_idx):
    return arr[row_idx, col_idx]

arr = np.array([[10, 20], [30, 40], [50, 60]])
rows = np.array([0, 1, 2])
cols = np.array([1, 0, 1])
print(extract_by_row_col(arr, rows, cols))


[20 30 60]


In [36]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr + 5)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 1, 1, 1],
                 [2, 2, 2, 2],
                 [3, 3, 3, 3]])
result = arr2 * arr1.T
print(result)

[[1 1 1 1]
 [4 4 4 4]
 [9 9 9 9]]


In [38]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
result = arr2 + arr1.T
print(result)

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [39]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20, 30]])
print(arr1 + arr2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [40]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
try:
    result = arr1 * arr2
except ValueError as e:
    print("Incompatible shapes:", e)

Incompatible shapes: operands could not be broadcast together with shapes (2,3) (2,2) 


In [41]:
# 41. Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))

[2.5 3.5 4.5]


In [42]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=1))

[3 6]


In [43]:
# 43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr, axis=0))

[1 1 1]


In [44]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr))

[[ 1  3  6]
 [ 4  9 15]]


In [45]:
# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(np.all(arr % 2 == 0, axis=0))

[False False False]


In [46]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [47]:
# 47. Create a function that takes a matrix as input and returns the flattened array.


input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()

print(flatten_matrix(input_matrix))

[1 2 3 4 5 6]


In [48]:
# 48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

print(concatenate_arrays(array1, array2, axis=0))
print(concatenate_arrays(array1, array2, axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [49]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(arr, num_splits, axis):
    return np.array_split(arr, num_splits, axis=axis)

print(split_array(original_array, 3, axis=0))
print(split_array(original_array, 3, axis=1))


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [50]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

inserted_array = np.insert(original_array, indices_to_insert, values_to_insert)
final_array = np.delete(inserted_array, indices_to_delete)
print(final_array)


[ 1 10  4 11  5]


In [51]:
# 51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.
arr1 = np.random.randint(1, 100, 10)
arr2 = np.arange(1, 11)

result = arr1 + arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)


arr1: [37 37 67 23  4 54 74 86 68  2]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
result: [38 39 70 27  9 60 81 94 77 12]


In [52]:
# 52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(arr1)
print(arr2)
print(result)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
# 53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.
arr1 = np.random.randint(1, 100, 5)
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 * arr2
print(arr1)
print(arr2)
print(result)

[74 78 95 98 79]
[1 2 3 4 5]
[ 74 156 285 392 395]


In [54]:
# 54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 / arr2
print(arr1)
print(arr2)
print(result)

[ 2  4  6  8 10]
[1 2 3 4 5]
[2. 2. 2. 2. 2.]


In [55]:
# 55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result = arr1 ** arr2
print(arr1)
print(arr2)
print(result)

[1 2 3 4 5]
[5 4 3 2 1]
[ 1 16 27 16  5]


In [56]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(array, substring):
    return np.char.count(array, substring).sum()

print(count_substring(arr, 'hello'))

3


In [57]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(array):
    return [''.join([ch for ch in word if ch.isupper()]) for word in array]

print(extract_uppercase(arr))

['H', 'W', 'OAI', 'GPT']


In [58]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(array, old, new):
    return np.char.replace(array, old, new)

print(replace_substring(arr, 'apple', 'mango'))


['mango' 'banana' 'grape' 'pinemango']


In [59]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_arrays(a, b):
    return np.char.add(a, b)

print(concatenate_arrays(arr1, arr2))
# 59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_arrays(a, b):
    return np.char.add(a, b)

print(concatenate_arrays(arr1, arr2))

['HelloOpen' 'WorldAI']
['HelloOpen' 'WorldAI']


In [60]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_length(array):
    return max([len(word) for word in array])

print(longest_length(arr))


9


In [61]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
data = np.random.randint(1, 1001, 100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print(mean)
print(median)
print(variance)
print(std_deviation)


526.39
535.5
73805.99790000002
271.6725932073385


In [62]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
data = np.random.randint(1, 101, 50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(percentile_25)
print(percentile_75)

24.25
67.5


In [63]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.
x = np.random.randint(1, 100, 10)
y = np.random.randint(1, 100, 10)

correlation = np.corrcoef(x, y)

print(x)
print(y)
print(correlation)


[35  1 93 93 60  4 77 11 90 77]
[68 65 95  4 55 62 17  9 59 56]
[[ 1.         -0.02787379]
 [-0.02787379  1.        ]]


In [64]:
# 64. Create two matrices and perform matrix multiplication using NumPy's dot function.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [65]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr = np.random.randint(10, 1001, 50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)

print(p10)
print(p50)
print(p90)
print(q1)
print(q3)

128.3
533.5
878.0
253.75
728.5


In [66]:
# 66. Create a NumPy array of integers and find the index of a specific element.
arr = np.array([5, 10, 15, 20, 25])
index = np.where(arr == 15)[0][0]
print(index)

2


In [67]:
# 67. Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(arr)
print(sorted_arr)

[ 6 16 17 24 29 36 70 75 86 88]


In [68]:
# 68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr > 20]
print(filtered)

[25 42 30]


In [69]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr % 3 == 0]
print(filtered)

[12 15]


In [70]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]
print(filtered)

[20 30 40]


In [71]:
# 71. For the given NumPy array, check its byte order using the dtype attribute byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [72]:
# 72. For the given NumPy array, perform byte swapping in place using byteswap().
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)

[16777216 33554432 50331648]


In [73]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using view().
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.view(arr.dtype.newbyteorder('S'))
print(new_arr)

[16777216 33554432 50331648]


In [74]:
# 74. For the given NumPy array, swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder in ('=', '<'):
    swapped = arr.view(arr.dtype.newbyteorder('>'))
else:
    swapped = arr.view(arr.dtype.newbyteorder('<'))
print(swapped)


[16777216 33554432 50331648]


In [75]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype.byteorder)

=


In [76]:
# 76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
copy_arr = arr1.copy()
copy_arr[0] = 99
print(arr1)
print(copy_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


In [77]:
# 77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.
matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[:, :2]
view_slice[0, 0] = 777
print(matrix)

[[777  65  66]
 [  1  15  81]
 [ 55  76  51]]


In [78]:
# 78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:, 1:]
view_b += 5
print(array_a)

[[ 1  7  8]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


In [79]:
# 79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 123
print(orig_array)


[[123   2   3   4]
 [  5   6   7   8]]


In [80]:
# 80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100
print(data)

[[9 9 5 6]
 [9 3 1 9]
 [1 1 7 6]]


In [81]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)
print(A - B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [82]:
# 82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
print(np.dot(C, D))

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [83]:
# 83. Create a matrix E and find its transpose.
E = np.array([[1, 2, 3], [4, 5, 6]])
print(E.T)

[[1 4]
 [2 5]
 [3 6]]


In [84]:
# 84. Generate a square matrix F and compute its determinant.
F = np.array([[1, 2], [3, 4]])
print(np.linalg.det(F))

-2.0000000000000004


In [85]:
# 85. Create a square matrix G and find its inverse.
G = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(G))

[[-2.   1. ]
 [ 1.5 -0.5]]
